[versions]
kotlin = "2.2.20"
shadow = "9.3.1"
architectury-loom = "1.13-SNAPSHOT"
architectury-plugin = "3.4-SNAPSHOT"
minecraft = "1.21.1"
neoforge = "21.1.182"
publish = "0.35.0"
matthiesen_core = "1.2.7"
sponge-mixin = "0.8.5"
luckperms = "5.4"
luckperms-mod = "dKAPoPGd" # v5.4.150 NeoForge (https://modrinth.com/plugin/luckperms/version/v5.4.150-neoforge)
mixinextras = "0.4.1"
adventure-mod = "6.0.0"
adventure-api = "4.17.0"
emberstextapi_version = "3.0.0"
forge-config-api-port = "21.1.6"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
architectury-loom = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }

[libraries]
publish = { group = "com.vanniktech", name = "gradle-maven-publish-plugin", version.ref = "publish" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
architectury-loom = { group = "dev.architectury", name = "architectury-loom", version.ref = "architectury-loom" }
architectury-plugin = { group = "architectury-plugin", name = "architectury-plugin.gradle.plugin", version.ref = "architectury-plugin" }
shadow-gradle = { group = "com.gradleup.shadow", name = "shadow-gradle-plugin", version.ref = "shadow" }
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
minecraft-net = { group = "net.minecraft", name = "minecraft", version.ref = "minecraft" }
neoforge = { group = "net.neoforged", name = "neoforge", version.ref = "neoforge" }
luckperms-api = { group = "net.luckperms", name = "api", version.ref = "luckperms" }
luckperms-mod = { group = "maven.modrinth", name = "luckperms", version.ref = "luckperms-mod" }
matthiesen-core-common = { group = "dev.matthiesen", name = "matthiesen-core-common", version.ref = "matthiesen_core" }
matthiesen-core-neoforge = { group = "dev.matthiesen", name = "matthiesen-core-neoforge", version.ref = "matthiesen_core" }
sponge-mixin = { group = "org.spongepowered", name = "mixin", version.ref = "sponge-mixin" }
mixinextras = { group = "io.github.llamalad7", name = "mixinextras-neoforge", version.ref = "mixinextras" }
adventure-mod-shared = { group = "net.kyori", name = "adventure-platform-mod-shared", version.ref = "adventure-mod" }
adventure-mod-neoforge = { group = "net.kyori", name = "adventure-platform-neoforge", version.ref = "adventure-mod" }
adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventure-api" }
minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventure-api" }
text-serializer = { group = "net.kyori", name = "adventure-text-serializer-json", version.ref = "adventure-api" }
emberstextapiNeoForge = { group = "net.tysontheember.emberstextapi", name = "emberstextapi-neoforge-1.21.1", version.ref = "emberstextapi_version" }
forge-config-api-port-common = { group = "fuzs.forgeconfigapiport", name = "forgeconfigapiport-common-neoforgeapi", version.ref = "forge-config-api-port" }

[bundles]
commonCompileOnly = ["luckperms-api", "sponge-mixin", "mixinextras", "forge-config-api-port-common"]
commonImplementation = ["minimessage", "text-serializer"]
commonModCompileOnly = ["adventure-mod-shared"]
commonModImplementationNoTransitive = ["matthiesen-core-common"]

neoforgeImplementation = ["adventure-api"]
neoforgeCompileOnly = ["luckperms-api"]
neoforgeRuntimeOnly = ["luckperms-mod"]
neoforgeImplementationInclude = ["adventure-mod-neoforge"]
neoforgeModImplementationNoTransitive = ["matthiesen-core-neoforge"]