modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = "A valid URL to your issue tracker where people can open bug tickets"
license = "MIT License"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Re-LPChatPrefix"
authors = "Adam Matthiesen"
description = '''
Luck Perms chat prefix designed with minimessage
'''
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"